services:
  postgres:
    image: postgres:15-alpine
    container_name: collabpad-postgres
    environment:
      POSTGRES_DB: collabpad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: collabpad-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  y-websocket:
    image: node:18-alpine
    container_name: collabpad-ywebsocket
    working_dir: /app
    command: sh -c "npm install -g y-websocket && HOST=0.0.0.0 PORT=1234 npx y-websocket-server"
    ports:
      - '1234:1234'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:1234 || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
