name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -l
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --dev
      - name: Generate Prisma client
        run: pnpm dlx prisma generate
      - name: Lint
        run: pnpm lint
      - name: Type check
        run: pnpm type-check
      - name: Run tests
        run: pnpm test
